import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Sparkles, ArrowRight, Cpu, Layers, Lock, Github, Linkedin, X } from 'lucide-react';
import useAuthStore from '../store/useAuthStore';

const TermsModal = ({ isOpen, onClose }) => {
    if (!isOpen) return null;
    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <motion.div 
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="bg-[#18181b] border border-white/10 rounded-2xl p-6 md:p-10 w-full max-w-3xl max-h-[85vh] overflow-y-auto shadow-2xl"
            >
                <div className="flex justify-between items-center mb-8 border-b border-white/10 pb-4">
                    <h2 className="text-3xl font-black text-white">Terms & Privacy</h2>
                    <button onClick={onClose} className="text-white/40 hover:text-white transition-colors bg-white/5 hover:bg-white/10 p-2 rounded-full">
                        <X size={20} />
                    </button>
                </div>
                <div className="space-y-6 text-white/70 text-sm md:text-base leading-relaxed">
                    <div>
                        <h3 className="text-lg font-bold text-white mb-2">1. Acceptance of Terms</h3>
                        <p>By accessing and using ChatterVerse, you agree to be bound by these terms. If you do not agree to all the terms and conditions, then you may not access the platform.</p>
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-white mb-2">2. Privacy & Data Usage</h3>
                        <p>Your privacy is our priority. Your chat data is stored securely in our database solely to provide you with chat history. We do not sell your personal conversations to third-party advertisers. Please note that AI providers (Google and OpenAI) receive your prompts temporarily in order to generate responses, in accordance with their respective API privacy policies.</p>
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-white mb-2">3. User Conduct</h3>
                        <p>You agree not to use the platform for any unlawful purposes, to harass others, to distribute malware, or to generate malicious, illegal, or highly harmful content. ChatterVerse reserves the right to suspend accounts that violate these guidelines.</p>
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-white mb-2">4. AI Limitations and Disclaimer</h3>
                        <p>Responses on this platform are generated by Artificial Intelligence. They may occasionally be inaccurate, biased, or inappropriate. ChatterVerse is provided "as is" without any warranties. We are not responsible for any decisions made based on AI-generated advice (especially medical, legal, or financial advice).</p>
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-white mb-2">5. Account Termination</h3>
                        <p>We reserve the right to modify, suspend, or terminate the service, or your access to it, at any time without notice, for any reason, including violation of these Terms.</p>
                    </div>
                    <div className="pt-6 mt-6 border-t border-white/5">
                        <p className="text-xs text-white/40 italic">Last updated: April 2026</p>
                    </div>
                </div>
            </motion.div>
        </div>
    );
};

const Landing = () => {
    const navigate = useNavigate();
    const { token } = useAuthStore();
    const [showTerms, setShowTerms] = useState(false);

    const handleStart = () => {
        if (token) navigate('/chat');
        else navigate('/signup');
    };

    const scrollToFeatures = () => {
        document.getElementById('features').scrollIntoView({ behavior: 'smooth' });
    };

    return (
        <div className="min-h-screen bg-[#09090b] text-[#fafafa] flex flex-col relative overflow-hidden font-sans">
            <TermsModal isOpen={showTerms} onClose={() => setShowTerms(false)} />

            {/* Background Soft Glows */}
            <div className="absolute top-[-20%] left-[-10%] w-[600px] h-[600px] bg-indigo-500/10 rounded-full blur-[120px] pointer-events-none" />
            <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] bg-purple-500/10 rounded-full blur-[120px] pointer-events-none" />

            {/* Navbar (Minimal) */}
            <nav className="w-full max-w-7xl mx-auto px-8 py-8 flex items-center justify-between z-20">
                <div className="flex items-center gap-2">
                    <div className="w-8 h-8 bg-indigo-500 rounded-lg flex items-center justify-center">
                        <Sparkles size={18} className="text-white" />
                    </div>
                    <span className="text-xl font-black tracking-tighter">ChatterVerse</span>
                </div>
                <button 
                  onClick={() => navigate('/login')}
                  className="text-sm font-bold text-white/40 hover:text-white transition-all"
                >
                    Sign In
                </button>
            </nav>

            {/* Hero Section */}
            <main className="flex-1 flex flex-col items-center justify-center p-8 z-10 text-center min-h-[80vh]">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8 }}
                    className="max-w-4xl"
                >
                    <motion.div 
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="mb-8 inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass border border-white/5 text-[10px] font-black uppercase tracking-[0.2em] text-indigo-400"
                    >
                        <Sparkles size={12} /> Next-Gen AI Platform
                    </motion.div>

                    <h1 className="text-6xl md:text-8xl font-black mb-8 leading-[0.9] tracking-tighter">
                        Intelligent. <br />
                        <span className="text-[#818cf8]">Articulate.</span> <br />
                        Yours.
                    </h1>

                    <p className="text-xl md:text-2xl text-white/40 font-medium mb-12 max-w-2xl mx-auto tracking-tight">
                        Experience the most articulate AI companion. <br className="hidden md:block" />
                        Designed for clarity, built for connection.
                    </p>

                    <div className="flex flex-col md:flex-row gap-4 justify-center items-center">
                        <button 
                            onClick={handleStart}
                            className="w-full md:w-auto px-10 py-5 bg-indigo-500 hover:bg-white hover:text-indigo-500 text-white text-lg font-black rounded-2xl transition-all shadow-lg active:scale-95 flex items-center justify-center gap-3 group"
                        >
                            Get Started 
                            <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
                        </button>
                        <button 
                            onClick={scrollToFeatures}
                            className="w-full md:w-auto px-10 py-5 glass border border-white/5 text-lg font-bold rounded-2xl hover:bg-white/5 transition-all text-white/60"
                        >
                            Explore Features
                        </button>
                    </div>
                </motion.div>

                {/* Social Proof / Stats (Minimal) */}
                <motion.div 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.8, duration: 1 }}
                    className="mt-24 grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-20 opacity-20 border-t border-white/5 pt-12 w-full max-w-5xl"
                >
                    {[
                        { label: "Active Threads", val: "2.4M" },
                        { label: "AI Moods", val: "Custom" },
                        { label: "Response Time", val: "0.2s" },
                        { label: "Built With", val: "Gemini" },
                    ].map((s, i) => (
                        <div key={i} className="text-center">
                            <p className="text-2xl font-black mb-1">{s.val}</p>
                            <p className="text-[10px] font-bold uppercase tracking-widest">{s.label}</p>
                        </div>
                    ))}
                </motion.div>
            </main>

            {/* Features Section */}
            <section id="features" className="w-full max-w-7xl mx-auto px-8 py-32 z-10">
                <div className="text-center mb-16">
                    <h2 className="text-4xl md:text-5xl font-black mb-4">Powered by the Best</h2>
                    <p className="text-xl text-white/40">Everything you need for the perfect conversation.</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {[
                        { icon: <Cpu className="text-indigo-400" size={32} />, title: "Multi-Model Engine", desc: "Switch instantly between Google Gemini 2.5 and OpenAI GPT-4o depending on your needs. The choice is yours." },
                        { icon: <Layers className="text-purple-400" size={32} />, title: "Custom Vibes", desc: "From 'Chill Buddy' to 'Teacher Mode', talk to AI with the personality that fits your exact mood and task." },
                        { icon: <Lock className="text-emerald-400" size={32} />, title: "Privacy First", desc: "Your chats are encrypted and securely stored. We respect your data privacy and keep your history safe." }
                    ].map((feat, i) => (
                        <motion.div 
                            key={i}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: i * 0.1 }}
                            className="bg-white/5 border border-white/5 rounded-3xl p-8 hover:bg-white/10 transition-colors"
                        >
                            <div className="mb-6 p-4 bg-black/50 rounded-2xl inline-block">{feat.icon}</div>
                            <h3 className="text-2xl font-bold mb-3">{feat.title}</h3>
                            <p className="text-white/50 leading-relaxed">{feat.desc}</p>
                        </motion.div>
                    ))}
                </div>
            </section>

            {/* How It Works */}
            <section className="w-full max-w-7xl mx-auto px-8 py-32 z-10 border-t border-white/5">
                <div className="text-center mb-16">
                    <h2 className="text-4xl md:text-5xl font-black mb-4">How It Works</h2>
                    <p className="text-xl text-white/40">Three simple steps to AI enlightenment.</p>
                </div>
                <div className="flex flex-col md:flex-row gap-8 justify-center max-w-5xl mx-auto">
                    {[
                        { step: "01", title: "Create Account", desc: "Sign up securely in seconds. Your data is synced and ready." },
                        { step: "02", title: "Select Your Vibe", desc: "Pick the AI personality and underlying model that you want to talk to." },
                        { step: "03", title: "Start Chatting", desc: "Experience real-time, fluid conversations with instant streaming responses." }
                    ].map((item, i) => (
                        <div key={i} className="flex-1 relative p-8 text-center md:text-left">
                            <div className="text-6xl font-black text-white/5 mb-4">{item.step}</div>
                            <h3 className="text-2xl font-bold mb-2">{item.title}</h3>
                            <p className="text-white/50 leading-relaxed">{item.desc}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Final CTA */}
            <section className="w-full max-w-5xl mx-auto px-8 py-32 z-10 text-center">
                <div className="bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-indigo-500/30 rounded-[3rem] p-12 md:p-24 relative overflow-hidden">
                    <div className="absolute inset-0 bg-black/20 mix-blend-overlay"></div>
                    <h2 className="text-4xl md:text-6xl font-black mb-6 relative z-10 tracking-tight">Ready to chat?</h2>
                    <p className="text-xl md:text-2xl text-white/60 mb-10 relative z-10 max-w-2xl mx-auto">Join thousands of users experiencing the future of AI conversation today.</p>
                    <button 
                        onClick={handleStart}
                        className="relative z-10 px-12 py-6 bg-white text-black text-xl font-black rounded-2xl hover:bg-indigo-50 transition-all shadow-[0_0_40px_rgba(255,255,255,0.2)] hover:scale-105 active:scale-95 flex items-center justify-center gap-3 mx-auto"
                    >
                        Launch ChatterVerse
                        <ArrowRight size={24} />
                    </button>
                </div>
            </section>

            {/* Footer */}
            <footer className="w-full max-w-7xl mx-auto px-8 py-12 flex flex-col md:flex-row items-center justify-between gap-6 border-t border-white/5 z-20">
                <div className="flex flex-col items-center md:items-start gap-3">
                    <div className="flex items-center gap-2 mb-1">
                        <Sparkles size={16} className="text-indigo-400" />
                        <span className="text-base font-black tracking-tighter">ChatterVerse</span>
                    </div>
                    <p className="text-[10px] font-bold text-white/30 uppercase tracking-[0.2em]">
                        © 2026 ChatterVerse Platform. All rights reserved.
                    </p>
                    <p className="text-xs text-white/40">Designed & Built by <span className="text-white/60 font-bold">Shreyansh Gupta</span></p>
                </div>
                
                <div className="flex gap-6 items-center">
                    <button 
                        onClick={() => setShowTerms(true)} 
                        className="text-[10px] font-bold text-white/40 hover:text-white uppercase tracking-widest transition-all px-4 py-2 hover:bg-white/5 rounded-lg"
                    >
                        Terms & Privacy
                    </button>
                    <div className="w-px h-4 bg-white/10 hidden md:block"></div>
                    <a href="https://github.com/ShreyanshGupta205" target="_blank" rel="noopener noreferrer" className="text-white/40 hover:text-white transition-all p-2 hover:bg-white/5 rounded-full">
                        <Github size={20} />
                    </a>
                    <a href="https://linkedin.com/in/shreyanshgupta205" target="_blank" rel="noopener noreferrer" className="text-white/40 hover:text-blue-400 transition-all p-2 hover:bg-white/5 rounded-full">
                        <Linkedin size={20} />
                    </a>
                </div>
            </footer>
        </div>
    );
};

export default Landing;
